CREATE TABLE guilds ();
CREATE TABLE client ();
CREATE TABLE verification_guild ();
CREATE TABLE verification_app ();
CREATE TABLE economy_role_income ();
CREATE TABLE economy_role_multiplier ();
CREATE TABLE purchasable_role ();
CREATE TABLE economy_guild ();
CREATE TABLE economy_user ();
CREATE TABLE modmail ();
CREATE TABLE modmail_guild ();
CREATE TABLE leveling_guild ();
CREATE TABLE leveling_role_multiplier ();
CREATE TABLE leveling_roles ();
CREATE TABLE leveling_user ();
CREATE TABLE _migrations ();
ALTER TABLE guilds ADD COLUMN guild_id BIGINT;
ALTER TABLE client ADD COLUMN id INTEGER;
ALTER TABLE client ADD COLUMN client_id BIGINT;
ALTER TABLE client ADD COLUMN maintenance_mode BOOLEAN;
ALTER TABLE client ADD COLUMN allowed_guilds BIGINT[];
ALTER TABLE client ADD COLUMN support_channel_id BIGINT;
ALTER TABLE verification_guild ADD COLUMN guild_id BIGINT;
ALTER TABLE verification_guild ADD COLUMN verification_logging_channel BIGINT;
ALTER TABLE verification_guild ADD COLUMN verification_questions TEXT[];
ALTER TABLE verification_guild ADD COLUMN unverified_role_ids BIGINT[];
ALTER TABLE verification_guild ADD COLUMN verified_role_ids BIGINT[];
ALTER TABLE verification_guild ADD COLUMN verification_instructions TEXT;
ALTER TABLE verification_guild ADD COLUMN pending_verifications_channel_id BIGINT;
ALTER TABLE verification_guild ADD COLUMN welcome_role_id BIGINT;
ALTER TABLE verification_guild ADD COLUMN welcome_channel_id BIGINT;
ALTER TABLE verification_guild ADD COLUMN welcome_message TEXT;
ALTER TABLE verification_guild ADD COLUMN joining_message TEXT;
ALTER TABLE verification_guild ADD COLUMN welcome_message_banner_url TEXT;
ALTER TABLE verification_guild ADD COLUMN staff_role_id BIGINT;
ALTER TABLE verification_app ADD COLUMN id SERIAL;
ALTER TABLE verification_app ADD COLUMN user_id BIGINT;
ALTER TABLE verification_app ADD COLUMN guild_id BIGINT;
ALTER TABLE verification_app ADD COLUMN pending_verification_id BIGINT;
ALTER TABLE verification_app ADD COLUMN questioning BOOLEAN;
ALTER TABLE verification_app ADD COLUMN questioning_channel_id BIGINT;
ALTER TABLE economy_role_income ADD COLUMN id SERIAL;
ALTER TABLE economy_role_income ADD COLUMN guild_id BIGINT;
ALTER TABLE economy_role_income ADD COLUMN role_id BIGINT;
ALTER TABLE economy_role_income ADD COLUMN min_income INTEGER;
ALTER TABLE economy_role_income ADD COLUMN max_income INTEGER;
ALTER TABLE economy_role_multiplier ADD COLUMN id SERIAL;
ALTER TABLE economy_role_multiplier ADD COLUMN guild_id BIGINT;
ALTER TABLE economy_role_multiplier ADD COLUMN role_id BIGINT;
ALTER TABLE economy_role_multiplier ADD COLUMN multiplier REAL;
ALTER TABLE purchasable_role ADD COLUMN id SERIAL;
ALTER TABLE purchasable_role ADD COLUMN guild_id BIGINT;
ALTER TABLE purchasable_role ADD COLUMN role_id BIGINT;
ALTER TABLE purchasable_role ADD COLUMN price INTEGER;
ALTER TABLE economy_guild ADD COLUMN guild_id BIGINT;
ALTER TABLE economy_guild ADD COLUMN economy_enabled BOOLEAN;
ALTER TABLE economy_guild ADD COLUMN economy_currency TEXT;
ALTER TABLE economy_guild ADD COLUMN economy_currency_on_left BOOLEAN;
ALTER TABLE economy_guild ADD COLUMN economy_starting_balance INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_maximum_balance INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_message_earnings_min INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_message_earnings_max INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_daily_amount_min INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_daily_amount_max INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_work_amount_min INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_work_amount_max INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_server_multiplier REAL;
ALTER TABLE economy_guild ADD COLUMN economy_earnable_messages_per_min INTEGER;
ALTER TABLE economy_guild ADD COLUMN economy_log_channel BIGINT;
ALTER TABLE economy_user ADD COLUMN guild_id BIGINT;
ALTER TABLE economy_user ADD COLUMN user_id BIGINT;
ALTER TABLE economy_user ADD COLUMN balance INTEGER;
ALTER TABLE economy_user ADD COLUMN last_daily DATE;
ALTER TABLE economy_user ADD COLUMN last_message DATE;
ALTER TABLE economy_user ADD COLUMN last_work DATE;
ALTER TABLE economy_user ADD COLUMN last_role_income DATE;
ALTER TABLE economy_user ADD COLUMN multiplier REAL;
ALTER TABLE modmail ADD COLUMN id SERIAL;
ALTER TABLE modmail ADD COLUMN user_id BIGINT;
ALTER TABLE modmail ADD COLUMN guild_id BIGINT;
ALTER TABLE modmail ADD COLUMN modmail_channel_id BIGINT;
ALTER TABLE modmail ADD COLUMN no_dm BOOLEAN;
ALTER TABLE modmail_guild ADD COLUMN guild_id BIGINT;
ALTER TABLE modmail_guild ADD COLUMN modmail_category_id BIGINT;
ALTER TABLE modmail_guild ADD COLUMN modmail_log_channel_id BIGINT;
ALTER TABLE modmail_guild ADD COLUMN modmail_instruction TEXT;
ALTER TABLE modmail_guild ADD COLUMN modmail_staff_role_id BIGINT;
ALTER TABLE leveling_guild ADD COLUMN guild_id BIGINT;
ALTER TABLE leveling_guild ADD COLUMN leveling_enabled BOOLEAN;
ALTER TABLE leveling_guild ADD COLUMN leveling_xp_per_message_min INTEGER;
ALTER TABLE leveling_guild ADD COLUMN leveling_xp_per_message_max INTEGER;
ALTER TABLE leveling_guild ADD COLUMN leveling_xp_per_message_levelup_msg TEXT;
ALTER TABLE leveling_guild ADD COLUMN leveling_xp_per_message_levelup_channel BIGINT;
ALTER TABLE leveling_guild ADD COLUMN leveling_server_multiplier REAL;
ALTER TABLE leveling_guild ADD COLUMN leveling_xp_base REAL;
ALTER TABLE leveling_guild ADD COLUMN leveling_earnable_messages_per_min INTEGER;
ALTER TABLE leveling_guild ADD COLUMN leveling_blacklisted_channel BIGINT[];
ALTER TABLE leveling_role_multiplier ADD COLUMN guild_id BIGINT;
ALTER TABLE leveling_role_multiplier ADD COLUMN role_id BIGINT;
ALTER TABLE leveling_role_multiplier ADD COLUMN multiplier REAL;
ALTER TABLE leveling_roles ADD COLUMN id SERIAL;
ALTER TABLE leveling_roles ADD COLUMN guild_id BIGINT;
ALTER TABLE leveling_roles ADD COLUMN level INTEGER;
ALTER TABLE leveling_roles ADD COLUMN role_id BIGINT;
ALTER TABLE leveling_user ADD COLUMN guild_id BIGINT;
ALTER TABLE leveling_user ADD COLUMN user_id BIGINT;
ALTER TABLE leveling_user ADD COLUMN xp INTEGER;
ALTER TABLE _migrations ADD COLUMN id_ INTEGER;
ALTER TABLE guilds ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE client ALTER COLUMN id SET NOT NULL;
ALTER TABLE client ALTER COLUMN client_id SET NOT NULL;
ALTER TABLE client ALTER COLUMN maintenance_mode SET NOT NULL;
ALTER TABLE client ALTER COLUMN allowed_guilds SET NOT NULL;
ALTER TABLE verification_guild ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE verification_guild ALTER COLUMN verification_questions SET NOT NULL;
ALTER TABLE verification_guild ALTER COLUMN unverified_role_ids SET NOT NULL;
ALTER TABLE verification_guild ALTER COLUMN verified_role_ids SET NOT NULL;
ALTER TABLE verification_app ALTER COLUMN id SET NOT NULL;
ALTER TABLE verification_app ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE verification_app ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE verification_app ALTER COLUMN pending_verification_id SET NOT NULL;
ALTER TABLE verification_app ALTER COLUMN questioning SET NOT NULL;
ALTER TABLE economy_role_income ALTER COLUMN id SET NOT NULL;
ALTER TABLE economy_role_income ALTER COLUMN min_income SET NOT NULL;
ALTER TABLE economy_role_income ALTER COLUMN max_income SET NOT NULL;
ALTER TABLE economy_role_multiplier ALTER COLUMN id SET NOT NULL;
ALTER TABLE economy_role_multiplier ALTER COLUMN multiplier SET NOT NULL;
ALTER TABLE purchasable_role ALTER COLUMN id SET NOT NULL;
ALTER TABLE purchasable_role ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE purchasable_role ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE purchasable_role ALTER COLUMN price SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_enabled SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_currency SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_currency_on_left SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_starting_balance SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_message_earnings_min SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_message_earnings_max SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_daily_amount_min SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_daily_amount_max SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_work_amount_min SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_work_amount_max SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_server_multiplier SET NOT NULL;
ALTER TABLE economy_guild ALTER COLUMN economy_earnable_messages_per_min SET NOT NULL;
ALTER TABLE economy_user ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE economy_user ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE economy_user ALTER COLUMN balance SET NOT NULL;
ALTER TABLE economy_user ALTER COLUMN multiplier SET NOT NULL;
ALTER TABLE modmail ALTER COLUMN id SET NOT NULL;
ALTER TABLE modmail ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE modmail ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE modmail ALTER COLUMN modmail_channel_id SET NOT NULL;
ALTER TABLE modmail ALTER COLUMN no_dm SET NOT NULL;
ALTER TABLE modmail_guild ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE leveling_guild ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE leveling_guild ALTER COLUMN leveling_enabled SET NOT NULL;
ALTER TABLE leveling_guild ALTER COLUMN leveling_xp_per_message_min SET NOT NULL;
ALTER TABLE leveling_guild ALTER COLUMN leveling_xp_per_message_max SET NOT NULL;
ALTER TABLE leveling_guild ALTER COLUMN leveling_server_multiplier SET NOT NULL;
ALTER TABLE leveling_guild ALTER COLUMN leveling_xp_base SET NOT NULL;
ALTER TABLE leveling_guild ALTER COLUMN leveling_earnable_messages_per_min SET NOT NULL;
ALTER TABLE leveling_role_multiplier ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE leveling_role_multiplier ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE leveling_role_multiplier ALTER COLUMN multiplier SET NOT NULL;
ALTER TABLE leveling_roles ALTER COLUMN id SET NOT NULL;
ALTER TABLE leveling_roles ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE leveling_roles ALTER COLUMN level SET NOT NULL;
ALTER TABLE leveling_roles ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE leveling_user ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE leveling_user ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE leveling_user ALTER COLUMN xp SET NOT NULL;
ALTER TABLE _migrations ALTER COLUMN id_ SET NOT NULL;
ALTER TABLE guilds ADD CONSTRAINT _guilds_guild_id_primary_key PRIMARY KEY ( guild_id );
ALTER TABLE client ADD CONSTRAINT _client_id_primary_key PRIMARY KEY ( id );
ALTER TABLE verification_guild ADD CONSTRAINT _verification_guild_guild_id_primary_key PRIMARY KEY ( guild_id );
ALTER TABLE verification_app ADD CONSTRAINT _verification_app_id_primary_key PRIMARY KEY ( id );
ALTER TABLE economy_role_income ADD CONSTRAINT _economy_role_income_id_primary_key PRIMARY KEY ( id );
ALTER TABLE economy_role_multiplier ADD CONSTRAINT _economy_role_multiplier_id_primary_key PRIMARY KEY ( id );
ALTER TABLE purchasable_role ADD CONSTRAINT _purchasable_role_id_primary_key PRIMARY KEY ( id );
ALTER TABLE economy_guild ADD CONSTRAINT _economy_guild_guild_id_primary_key PRIMARY KEY ( guild_id );
ALTER TABLE economy_user ADD CONSTRAINT _economy_user_guild_id_user_id_primary_key PRIMARY KEY ( guild_id , user_id );
ALTER TABLE modmail ADD CONSTRAINT _modmail_id_primary_key PRIMARY KEY ( id );
ALTER TABLE modmail_guild ADD CONSTRAINT _modmail_guild_guild_id_primary_key PRIMARY KEY ( guild_id );
ALTER TABLE leveling_guild ADD CONSTRAINT _leveling_guild_guild_id_primary_key PRIMARY KEY ( guild_id );
ALTER TABLE leveling_role_multiplier ADD CONSTRAINT _leveling_role_multiplier_role_id_primary_key PRIMARY KEY ( role_id );
ALTER TABLE leveling_roles ADD CONSTRAINT _leveling_roles_guild_id_id_primary_key PRIMARY KEY ( guild_id , id );
ALTER TABLE leveling_user ADD CONSTRAINT _leveling_user_guild_id_user_id_primary_key PRIMARY KEY ( guild_id , user_id );
ALTER TABLE _migrations ADD CONSTRAINT __migrations_id__primary_key PRIMARY KEY ( id_ );